discover_devices:
  name: Discover Devices
  description: Trigger manual discovery of Fluora devices on the network.
  fields: {}

clear_discovered_devices:
  name: Clear Discovered Devices
  description: Clear the list of discovered devices from the PixelAirClient.
  fields: {}

send_discovery_broadcast:
  name: Send Discovery Broadcast
  description: Send a discovery broadcast to find new devices.
  fields: {}
